### ISSUE TITLE
Theres no shopping cart

### ISSUE THREAD

**Issue by tlcowling** [jaredledvina/ledvinafarm-site#2]
I first heard of the Ledvina farm by way of word of mouth from one of those nice Baristas in the Ann Arbor.

I was dismayed to find that after typing ledvina farm into the google search bar then clicking the top link, I could not find a shopping cart anywhere.

I want to buy some organic farm-fresh real actual milk from a cow.

**Comment by jaredledvina** [comment]
Sorry to disappoint, at this point in time, the Ledvina Farm does not have the capability to facilitate online orders.
